import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/Utils/ReactQuery/QueryProvider";
import Footer from "@/modules/footer/views/Footer";
import Navbar from "@/modules/header/views/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Navbar />
          <div className="pt-[83px]">{children}</div>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
