import type { Metadata } from "next";

import "./globals.css";
import Layouts from "@/components/Layouts/Layouts";
import QueryProvider from "@/Utils/ReactQuery/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Layouts>{children}</Layouts>
        </QueryProvider>
      </body>
    </html>
  );
}
